aws_region          = "us-east-1"
project_id          = "cmtr-zdv1y551"
vpc_name            = "cmtr-zdv1y551-vpc"
public_subnet_name  = "cmtr-zdv1y551-public-subnet-1"
security_group_name = "cmtr-zdv1y551-sg"
instance_name       = "cmtr-zdv1y551-instance"
instance_type       = "t2.micro" 